-d E:\sipeed\Tang\Tang-Nano-examples-master\example_lcd\lcd_pjt\impl\gwsynthesis\lcd_pjt.vg
-p GW1NZ-1-QFN48-6
-pn GW1NZ-LV1QN48C6/I5
-cst E:\sipeed\Tang\Tang-Nano-examples-master\example_lcd\lcd_pjt\src\rgb_psram.cst
-cfg E:\sipeed\Tang\Tang-Nano-examples-master\example_lcd\lcd_pjt\impl\pnr\device.cfg
-bit
-tr
-ph
-timing
-cst_error
