-d E:\sipeed\Tang\Tang-Nano-examples-master\example_led\led_prj\impl\gwsynthesis\led_prj.vg
-p GW1NZ-1-QFN48-6
-pn GW1NZ-LV1QN48C6/I5
-cst E:\sipeed\Tang\Tang-Nano-examples-master\example_led\led_prj\src\led_prj.cst
-cfg E:\sipeed\Tang\Tang-Nano-examples-master\example_led\led_prj\impl\pnr\device.cfg
-bit
-tr
-ph
-timing
-cst_error
